Implement Tag and Untag Feature for Video, Module, and Lecture
AY2223S2-CS2103-F10-2/tp pull request #114
Opened 2023-03-17 17:51 UTC by lennoxtr

close #85
close #86  
close #87

2023-03-17 23:55 UTC, shaowi commented
please update your code to pass the tests

2023-03-18 03:39 UTC, shaowi commented on src/main/java/seedu/address/logic/commands/UntagCommand.java
> +    public static final String MESSAGE_VIDEO_NOT_FOUND = "Video doesn't exist in this lecture";
Can possibly use the Messages.java instead? If any variable is not available there, you can move them it there

2023-03-18 03:44 UTC, shaowi commented on src/test/java/seedu/address/logic/parser/ParseArgumentTest.java
Can we remove this file?

2023-03-18 03:48 UTC, shaowi requested changes
Please update accordingly to my comments

2023-03-18 03:48 UTC, shaowi commented on src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Same comments as ParseArgumentsTest.java file

2023-03-18 04:05 UTC, shaowi requested changes

2023-03-18 04:05 UTC, shaowi commented on src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Did u miss out on removing this file?

2023-03-18 04:12 UTC, lennoxtr commented on src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
I removed the file

2023-03-18 04:15 UTC, shaowi approved these changes
LGTM

2023-03-18 04:15 UTC, merged